version: 0.0
os: linux

# 配置するファイルの定義
files:
  - source: /index.html
    destination: /var/www/html/
    overwrite: yes  # 既存ファイルがあっても上書きする

# デプロイフックの定義
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

    - location: scripts/start_server
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/embed_env.sh
      timeout: 300
      runas: root
